### ISSUE TITLE
rename this repo to grpc?

### ISSUE THREAD

**Issue by miekg** [coredns/grpc#4]
see subject.

**Comment by johnbelamaric** [comment]
Sure

**Comment by johnbelamaric** [comment]
Done.

**Comment by johnbelamaric** [comment]
Hmm. If we think we may have several out-of-tree middleware repos, maybe we should make them easy to identify? It's long, but maybe something like "middleware-grpc" for the repo name?

**Comment by miekg** [comment]
I like "grpc" more, because it is shorter. Usually you will hit the repo directly and there is always a README explaining things.
